//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisionTIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lector()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int Identifiacion { get; set; }
        public string NombreLector { get; set; }
        public Nullable<System.DateTime> FechaNacimientoLec { get; set; }
        public Nullable<int> TelefonoLector { get; set; }
        public string CorreoLector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}
